### ISSUE TITLE
Feature: Form improvement

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#2114]
Forms deserves small improvements. As some tasks are more difficult than others, I open this issue to track them down.
See #2108.

**Todo list and propositions:**

- [ ] add a `blurCallback`. There can be a lot of change events, so we could need an intermediate callback in addition to `changeCallback`. Not sure how to implement it though.

- [ ] Split logic. `Form` and `FormComponents` have become...well... quite huge. I'd like to split them up a bit with a more functional logic. First, I think we could separate the "schema to fields" transformations (like `createField` method), because they are becoming quite complex with the support of arrays, arrays of items, etc. They could be handled in a pure JS file instead of belonging to a React component.

Then we can define containers for similar features. I think error management, current state management, submission management, fields computations, for example. They might be tied together so it's not trivial but I'm sure we can figure this out.

- [ ] Support nested schema with identic keys. The schema flattening currently makes this impossible (eg if your "recipe" as a `name` field and a `ingredients` array, and your "ingredient" schema also have a `name` field, you will have trouble). Might be hard though.

- [ ] allow to pass a `document` prop instead of `documentId` to the SmartForm. 
When passing a `document` prop, the form is filled as expected but edit fails, as there is no `updateWhatever` method. The `FormWrapper` seems to expect a `documentId` prop and ignore `document`. We can define `documentId` too but then the document is fetched again. Useful if data fetching is handled by the parent form.

- [ ] handle documentId change. Data seems not to be loaded if the documentId changes dynamically (seems to be a regression from the last update? or an underlying bug)? This might be due to the FormWrapper doing its computations in the consturctor.
- [x] Support custom input for arrays of objects. Right now the `input` prop is ignored (e.g `"address.$" :{ type: new SimpleSchema({...}), input: "ThisInputIsIgnored"}`). It needs small tweaks in the `schema_utils` file, and maybe to define a unified approach for `nestedFields` and `arrayField`.
- [x] Review `FormComponentInner`, which belongs to the bootstrap package. RIght now it's logic is duplicate in `vulcan:material-ui` and creates issue (can't override input of arrays)
